### PR TITLE
Library module support

### PR DESCRIPTION
**Pull request by ynnadrules**
Uses library plugin if project is library, app plugin otherwise.

### CODE REVIEW

**Comment by kalperin** [comment]
@ynnadrules is this one still relevant?  What i remember is that this was superseded by something upstream.  If so, then let's close it.  If not then i can review and clear it out.

**Comment by ynnadrules** [comment]
@kalperin maybe. It might actually be the version of the plug-in we're using. It's been a while though so I'll have to check.

**Comment by ynnadrules** [comment]
Were you able to address the conflicts?

**Comment by kalperin** [comment]
> Were you able to address the conflicts?

Nope.  My goal was to be able to build MobileToolboxNavigation without Bintray so i didn't try to solve that problem.

**Comment by ynnadrules** [comment]
> Nope. My goal was to be able to build MobileToolboxNavigation without Bintray so i didn't try to solve that problem.

Gotcha. I just realized this was my PR haha.

**Pull request merged**
